### ISSUE TITLE
Editor will not load

### ISSUE THREAD

**Issue by jojiklmts** [mrSkortch/DCS-ME_coalition-modification#2]
DCS version 2.5.6
After copying the mod the mission editor will not start. The loading screen will get stuck on "Terrain Graphics Init : 97 caucasus.ng5"

**Comment by mrSkortch** [comment]
After years trying to convince them that it not only was possible and works, but was a highly desired feature they finally added it to the game. The icon for it is on the left tool bar in the mission editor. This mod no longer needs to be installed. Run a repair to restore the default files. 

Third item under DCS World: 

https://forums.eagle.ru/topic/170893-dcs-world-25-changelog-and-updates-of-open-beta/?do=findComment&comment=4509488

**Comment by jojiklmts** [comment]
Dude you are so nice to reply to me. Thanks a lot!
